# Generated by Django 5.2.8 on 2025-11-11 02:28

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApothecaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('form', models.CharField(max_length=50)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('price_usd', models.FloatField(blank=True, null=True)),
                ('price_per_oz_usd', models.FloatField(blank=True, null=True)),
                ('stock_oz', models.FloatField(blank=True, null=True)),
                ('volume_ml', models.FloatField(blank=True, null=True)),
                ('container_size_g', models.FloatField(blank=True, null=True)),
                ('dosage', models.TextField(blank=True, null=True)),
                ('application', models.TextField(blank=True, null=True)),
                ('preparation', models.TextField(blank=True, null=True)),
                ('uses', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('ingredients', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('safety_notes', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
    ]
