# Generated by Django 5.2.8 on 2025-11-11 11:43

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micmnis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apothecaryitem',
            name='ingredients',
            field=models.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='safety_notes',
            field=models.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='uses',
            field=models.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
