# Generated by Django 5.2.8 on 2025-11-11 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micmnis', '0003_alter_apothecaryitem_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='apothecaryitem',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='apothecaryitem',
            name='price_per_oz_usd',
        ),
        migrations.RemoveField(
            model_name='apothecaryitem',
            name='safety_notes',
        ),
        migrations.RemoveField(
            model_name='apothecaryitem',
            name='uses',
        ),
        migrations.AddField(
            model_name='apothecaryitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='application',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='container_size_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='dosage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='form',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='preparation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='stock_oz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='type',
            field=models.CharField(choices=[('HERB', 'Herb'), ('TINC', 'Tincture'), ('BALM', 'Balm'), ('OIL', 'Essential Oil'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='volume_ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('items', models.ManyToManyField(blank=True, related_name='ingredients', to='micmnis.apothecaryitem')),
            ],
        ),
        migrations.AlterField(
            model_name='apothecaryitem',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='micmnis.origin'),
        ),
        migrations.CreateModel(
            name='SafetyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('items', models.ManyToManyField(blank=True, related_name='safety_notes', to='micmnis.apothecaryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('items', models.ManyToManyField(blank=True, related_name='uses', to='micmnis.apothecaryitem')),
            ],
        ),
    ]
