# Generated by Django 5.2.8 on 2025-11-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micmnis', '0004_origin_remove_apothecaryitem_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apothecaryitem',
            name='form',
        ),
    ]
